[directory]
truncation_length = 8
truncate_to_repo = false
[pixi]
disabled = true
[aws]
disabled = true
[lua]
disabled = true
[custom.current_dir]
command = "printf '\\e]%s\\e\\\\' '51;A'(whoami)'@'(hostname)':'(pwd)"
when = "true"
